services:
  - type: web
    name: steam-idler
    runtime: node
    envVars:
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
    buildCommand: "npm install"
    startCommand: "node index.js"
    healthCheckPath: "/health"
